2024-07-17 10:48:46,181 INFO    StreamThr :26400 [internal.py:wandb_internal():85] W&B internal server running at pid: 26400, started at: 2024-07-17 10:48:46.180326
2024-07-17 10:48:46,182 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: status
2024-07-17 10:48:46,187 INFO    WriterThread:26400 [datastore.py:open_for_write():87] open: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\run-ishnh8z9.wandb
2024-07-17 10:48:46,188 DEBUG   SenderThread:26400 [sender.py:send():379] send: header
2024-07-17 10:48:46,189 DEBUG   SenderThread:26400 [sender.py:send():379] send: run
2024-07-17 10:48:46,423 INFO    SenderThread:26400 [dir_watcher.py:__init__():211] watching files in: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files
2024-07-17 10:48:46,433 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: check_version
2024-07-17 10:48:46,438 INFO    SenderThread:26400 [sender.py:_start_run_threads():1188] run started: ishnh8z9 with start time 1721227726.185328
2024-07-17 10:48:46,439 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: check_version
2024-07-17 10:48:46,491 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: run_start
2024-07-17 10:48:46,563 DEBUG   HandlerThread:26400 [system_info.py:__init__():26] System info init
2024-07-17 10:48:46,563 DEBUG   HandlerThread:26400 [system_info.py:__init__():41] System info init done
2024-07-17 10:48:46,563 INFO    HandlerThread:26400 [system_monitor.py:start():194] Starting system monitor
2024-07-17 10:48:46,563 INFO    SystemMonitor:26400 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-07-17 10:48:46,563 INFO    HandlerThread:26400 [system_monitor.py:probe():214] Collecting system info
2024-07-17 10:48:46,568 INFO    SystemMonitor:26400 [interfaces.py:start():188] Started cpu monitoring
2024-07-17 10:48:46,568 INFO    SystemMonitor:26400 [interfaces.py:start():188] Started disk monitoring
2024-07-17 10:48:46,569 INFO    SystemMonitor:26400 [interfaces.py:start():188] Started gpu monitoring
2024-07-17 10:48:46,577 INFO    SystemMonitor:26400 [interfaces.py:start():188] Started memory monitoring
2024-07-17 10:48:46,581 INFO    SystemMonitor:26400 [interfaces.py:start():188] Started network monitoring
2024-07-17 10:48:46,589 DEBUG   HandlerThread:26400 [system_info.py:probe():152] Probing system
2024-07-17 10:48:46,590 DEBUG   HandlerThread:26400 [gitlib.py:_init_repo():56] git repository is invalid
2024-07-17 10:48:46,590 DEBUG   HandlerThread:26400 [system_info.py:probe():200] Probing system done
2024-07-17 10:48:46,590 DEBUG   HandlerThread:26400 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.19044-SP0', 'python': '3.11.9', 'heartbeatAt': '2024-07-17T14:48:46.589679', 'startedAt': '2024-07-17T14:48:46.149061', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'd:\\Works\\SomeCodes\\testing-wandb\\test-wandb.py', 'codePathLocal': 'test-wandb.py', 'codePath': 'test-wandb.py', 'host': 'PD-505W7Y3', 'username': '4475358', 'executable': 'C:\\ProgramData\\miniconda3\\envs\\wandbtestp11\\python.exe', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 2100.0, 'min': 0.0, 'max': 2100.0}, 'cpu_freq_per_core': [{'current': 2100.0, 'min': 0.0, 'max': 2100.0}], 'disk': {'/': {'total': 3726.0058555603027, 'used': 565.4866600036621}}, 'gpu': 'NVIDIA RTX A4500', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA RTX A4500', 'memory_total': 21464350720}], 'memory': {'total': 127.69602584838867}}
2024-07-17 10:48:46,590 INFO    HandlerThread:26400 [system_monitor.py:probe():224] Finished collecting system info
2024-07-17 10:48:46,590 INFO    HandlerThread:26400 [system_monitor.py:probe():227] Publishing system info
2024-07-17 10:48:46,590 DEBUG   HandlerThread:26400 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-07-17 10:48:47,428 INFO    Thread-16 :26400 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\conda-environment.yaml
2024-07-17 10:48:47,906 DEBUG   HandlerThread:26400 [system_info.py:_save_conda():224] Saving conda packages done
2024-07-17 10:48:47,907 INFO    HandlerThread:26400 [system_monitor.py:probe():229] Finished publishing system info
2024-07-17 10:48:47,916 DEBUG   SenderThread:26400 [sender.py:send():379] send: files
2024-07-17 10:48:47,916 INFO    SenderThread:26400 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-07-17 10:48:48,008 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: python_packages
2024-07-17 10:48:48,008 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: python_packages
2024-07-17 10:48:48,008 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: stop_status
2024-07-17 10:48:48,009 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: internal_messages
2024-07-17 10:48:48,009 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: stop_status
2024-07-17 10:48:48,013 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: partial_history
2024-07-17 10:48:48,014 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: server_info
2024-07-17 10:48:48,119 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-metadata.json?Expires=1721314127&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NGG0rTtVplkZfiGLvfFKD7cUeLbfqz%2BGCzDKiaAprYzhNBM6%2B8CFULGjRYmPlAtEQoUc%2BRIkmFkRjfPIK%2FSjlSq8eJgN1OiNDGaPwoRnjOsj20Ke%2Bhe3m%2BtrtqcrI%2B8p%2B7vCwVUBPuxSDtGt8DAEBHbwnIUrJngjkO0KJ4bWQZnRFX3jADnmvkzoNsMyZN9tYvhqq5GPdUuYMu1PJVNdaZmwFtbuxXZnaWEhStvhjWMiRw6ysql7y0zChU0N4WTG6bspmoutMuwHBjjM71Pu2Hyslc%2FCdSWB%2BmC0hn7GTK0c9cLfjkIb1DPxk7xGmXsh4SK76QqEcpbpL6B6iQDLJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-metadata.json?Expires=1721314127&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NGG0rTtVplkZfiGLvfFKD7cUeLbfqz%2BGCzDKiaAprYzhNBM6%2B8CFULGjRYmPlAtEQoUc%2BRIkmFkRjfPIK%2FSjlSq8eJgN1OiNDGaPwoRnjOsj20Ke%2Bhe3m%2BtrtqcrI%2B8p%2B7vCwVUBPuxSDtGt8DAEBHbwnIUrJngjkO0KJ4bWQZnRFX3jADnmvkzoNsMyZN9tYvhqq5GPdUuYMu1PJVNdaZmwFtbuxXZnaWEhStvhjWMiRw6ysql7y0zChU0N4WTG6bspmoutMuwHBjjM71Pu2Hyslc%2FCdSWB%2BmC0hn7GTK0c9cLfjkIb1DPxk7xGmXsh4SK76QqEcpbpL6B6iQDLJw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:48,119 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:48:48,119 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:48,216 DEBUG   SenderThread:26400 [sender.py:send():379] send: telemetry
2024-07-17 10:48:48,216 DEBUG   SenderThread:26400 [sender.py:send():379] send: history
2024-07-17 10:48:48,216 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: summary_record
2024-07-17 10:48:48,218 INFO    SenderThread:26400 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-07-17 10:48:48,218 DEBUG   SenderThread:26400 [sender.py:send():379] send: telemetry
2024-07-17 10:48:48,218 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: server_info
2024-07-17 10:48:48,284 DEBUG   SenderThread:26400 [sender.py:send():379] send: exit
2024-07-17 10:48:48,284 INFO    SenderThread:26400 [sender.py:send_exit():586] handling exit code: 0
2024-07-17 10:48:48,284 INFO    SenderThread:26400 [sender.py:send_exit():588] handling runtime: 1
2024-07-17 10:48:48,289 INFO    SenderThread:26400 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-07-17 10:48:48,289 INFO    SenderThread:26400 [sender.py:send_exit():594] send defer
2024-07-17 10:48:48,289 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:48,289 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 0
2024-07-17 10:48:48,289 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:48,290 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 0
2024-07-17 10:48:48,290 INFO    SenderThread:26400 [sender.py:transition_state():614] send defer: 1
2024-07-17 10:48:48,290 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:48,290 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 1
2024-07-17 10:48:48,290 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:48,290 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 1
2024-07-17 10:48:48,290 INFO    SenderThread:26400 [sender.py:transition_state():614] send defer: 2
2024-07-17 10:48:48,290 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:48,290 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 2
2024-07-17 10:48:48,290 INFO    HandlerThread:26400 [system_monitor.py:finish():203] Stopping system monitor
2024-07-17 10:48:48,291 INFO    HandlerThread:26400 [interfaces.py:finish():200] Joined cpu monitor
2024-07-17 10:48:48,291 DEBUG   SystemMonitor:26400 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-07-17 10:48:48,291 DEBUG   SystemMonitor:26400 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-07-17 10:48:48,303 DEBUG   SystemMonitor:26400 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-07-17 10:48:48,303 INFO    HandlerThread:26400 [interfaces.py:finish():200] Joined disk monitor
2024-07-17 10:48:48,368 INFO    HandlerThread:26400 [interfaces.py:finish():200] Joined gpu monitor
2024-07-17 10:48:48,369 INFO    HandlerThread:26400 [interfaces.py:finish():200] Joined memory monitor
2024-07-17 10:48:48,369 INFO    HandlerThread:26400 [interfaces.py:finish():200] Joined network monitor
2024-07-17 10:48:48,369 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:48,369 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 2
2024-07-17 10:48:48,369 INFO    SenderThread:26400 [sender.py:transition_state():614] send defer: 3
2024-07-17 10:48:48,369 DEBUG   SenderThread:26400 [sender.py:send():379] send: stats
2024-07-17 10:48:48,369 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:48,369 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 3
2024-07-17 10:48:48,370 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:48,370 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 3
2024-07-17 10:48:48,370 INFO    SenderThread:26400 [sender.py:transition_state():614] send defer: 4
2024-07-17 10:48:48,370 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:48,370 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 4
2024-07-17 10:48:48,370 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:48,370 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 4
2024-07-17 10:48:48,370 INFO    SenderThread:26400 [sender.py:transition_state():614] send defer: 5
2024-07-17 10:48:48,370 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:48,370 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 5
2024-07-17 10:48:48,370 DEBUG   SenderThread:26400 [sender.py:send():379] send: summary
2024-07-17 10:48:48,374 INFO    SenderThread:26400 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-07-17 10:48:48,374 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:48,374 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 5
2024-07-17 10:48:48,374 INFO    SenderThread:26400 [sender.py:transition_state():614] send defer: 6
2024-07-17 10:48:48,375 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:48,375 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 6
2024-07-17 10:48:48,375 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:48,375 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 6
2024-07-17 10:48:48,376 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: status_report
2024-07-17 10:48:48,435 INFO    Thread-16 :26400 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\conda-environment.yaml
2024-07-17 10:48:48,436 INFO    Thread-16 :26400 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\requirements.txt
2024-07-17 10:48:48,436 INFO    Thread-16 :26400 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\wandb-summary.json
2024-07-17 10:48:48,436 INFO    Thread-16 :26400 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\wandb-metadata.json
2024-07-17 10:48:48,456 INFO    SenderThread:26400 [sender.py:transition_state():614] send defer: 7
2024-07-17 10:48:48,456 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:48,456 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 7
2024-07-17 10:48:48,457 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:48,457 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 7
2024-07-17 10:48:48,457 INFO    SenderThread:26400 [sender.py:transition_state():614] send defer: 8
2024-07-17 10:48:48,457 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:48,457 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 8
2024-07-17 10:48:48,457 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:48,457 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 8
2024-07-17 10:48:48,457 INFO    SenderThread:26400 [job_builder.py:build():440] Attempting to build job artifact
2024-07-17 10:48:48,458 INFO    SenderThread:26400 [job_builder.py:_get_source_type():580] no source found
2024-07-17 10:48:48,458 INFO    SenderThread:26400 [sender.py:transition_state():614] send defer: 9
2024-07-17 10:48:48,458 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:48,458 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 9
2024-07-17 10:48:48,459 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:48,459 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 9
2024-07-17 10:48:48,459 INFO    SenderThread:26400 [dir_watcher.py:finish():358] shutting down directory watcher
2024-07-17 10:48:49,289 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:49,326 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-metadata.json?Expires=1721314127&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NGG0rTtVplkZfiGLvfFKD7cUeLbfqz%2BGCzDKiaAprYzhNBM6%2B8CFULGjRYmPlAtEQoUc%2BRIkmFkRjfPIK%2FSjlSq8eJgN1OiNDGaPwoRnjOsj20Ke%2Bhe3m%2BtrtqcrI%2B8p%2B7vCwVUBPuxSDtGt8DAEBHbwnIUrJngjkO0KJ4bWQZnRFX3jADnmvkzoNsMyZN9tYvhqq5GPdUuYMu1PJVNdaZmwFtbuxXZnaWEhStvhjWMiRw6ysql7y0zChU0N4WTG6bspmoutMuwHBjjM71Pu2Hyslc%2FCdSWB%2BmC0hn7GTK0c9cLfjkIb1DPxk7xGmXsh4SK76QqEcpbpL6B6iQDLJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-metadata.json?Expires=1721314127&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NGG0rTtVplkZfiGLvfFKD7cUeLbfqz%2BGCzDKiaAprYzhNBM6%2B8CFULGjRYmPlAtEQoUc%2BRIkmFkRjfPIK%2FSjlSq8eJgN1OiNDGaPwoRnjOsj20Ke%2Bhe3m%2BtrtqcrI%2B8p%2B7vCwVUBPuxSDtGt8DAEBHbwnIUrJngjkO0KJ4bWQZnRFX3jADnmvkzoNsMyZN9tYvhqq5GPdUuYMu1PJVNdaZmwFtbuxXZnaWEhStvhjWMiRw6ysql7y0zChU0N4WTG6bspmoutMuwHBjjM71Pu2Hyslc%2FCdSWB%2BmC0hn7GTK0c9cLfjkIb1DPxk7xGmXsh4SK76QqEcpbpL6B6iQDLJw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:49,326 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:48:49,327 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:49,442 INFO    SenderThread:26400 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\config.yaml
2024-07-17 10:48:49,443 INFO    SenderThread:26400 [dir_watcher.py:finish():388] scan: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files
2024-07-17 10:48:49,443 INFO    SenderThread:26400 [dir_watcher.py:finish():402] scan save: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\conda-environment.yaml conda-environment.yaml
2024-07-17 10:48:49,443 INFO    SenderThread:26400 [dir_watcher.py:finish():402] scan save: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\config.yaml config.yaml
2024-07-17 10:48:49,444 INFO    SenderThread:26400 [dir_watcher.py:finish():402] scan save: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\requirements.txt requirements.txt
2024-07-17 10:48:49,447 INFO    SenderThread:26400 [dir_watcher.py:finish():402] scan save: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\wandb-metadata.json wandb-metadata.json
2024-07-17 10:48:49,447 INFO    SenderThread:26400 [dir_watcher.py:finish():402] scan save: D:\Works\SomeCodes\testing-wandb\wandb\run-20240717_104846-ishnh8z9\files\wandb-summary.json wandb-summary.json
2024-07-17 10:48:49,449 INFO    SenderThread:26400 [sender.py:transition_state():614] send defer: 10
2024-07-17 10:48:49,449 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:48:49,450 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: defer
2024-07-17 10:48:49,450 INFO    HandlerThread:26400 [handler.py:handle_request_defer():184] handle defer: 10
2024-07-17 10:48:49,452 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: defer
2024-07-17 10:48:49,452 INFO    SenderThread:26400 [sender.py:send_request_defer():610] handle sender defer: 10
2024-07-17 10:48:49,452 INFO    SenderThread:26400 [file_pusher.py:finish():169] shutting down file pusher
2024-07-17 10:48:49,583 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/conda-environment.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WX8ySpKkxR7NeIRfOJE90zRpnaGZVqbP0aB1wpn%2FSg1qhNalNT4xoQ149%2BajNtMOqdN6yHlY2O0ioHbxw5Mml1S4fGOLM%2BnxGMrnVte6KhIBkSwxz9HJuSrrPDkxwTJEaDZ1E7nVAeHNbkM9%2BMxQE9duRXD9hHC8Ci6GOyzrC%2FjYFoduP3eZ3yp7aTCg%2Fi5NMMA%2BdeS6QFudN%2BXo2XmapJUzvABhqsMULVa9DmfR6ByVpImzCAfh4U0o24RiLCgKQc9uZzg8sSzcj7OYsPPq12hJbyADemZzEwu54nUXJR5HIv8E2dxrXlPwwyR01K7%2Fn7Uu6S1Epc9gm7A42dP%2F2g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/conda-environment.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WX8ySpKkxR7NeIRfOJE90zRpnaGZVqbP0aB1wpn%2FSg1qhNalNT4xoQ149%2BajNtMOqdN6yHlY2O0ioHbxw5Mml1S4fGOLM%2BnxGMrnVte6KhIBkSwxz9HJuSrrPDkxwTJEaDZ1E7nVAeHNbkM9%2BMxQE9duRXD9hHC8Ci6GOyzrC%2FjYFoduP3eZ3yp7aTCg%2Fi5NMMA%2BdeS6QFudN%2BXo2XmapJUzvABhqsMULVa9DmfR6ByVpImzCAfh4U0o24RiLCgKQc9uZzg8sSzcj7OYsPPq12hJbyADemZzEwu54nUXJR5HIv8E2dxrXlPwwyR01K7%2Fn7Uu6S1Epc9gm7A42dP%2F2g%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:49,583 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:48:49,583 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:49,591 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/config.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aFO1ri7b49f8ypxktMGRu5N8KOKNbziyLqleUH09MPuA9PAYZ%2FUEkzNPS3oRL0qGvnykBS1HQtgfvNCRTijfwD2pBGklHVDw8PW2AdH3Vxwf1m6Z96Qh%2FZVyaFAMruifaFo1jxASWgELM6qrkGn856Aisqe%2B6dpUJgxU7vtPajwRGPMhw4jQEsZyN4xP%2FTpi7T%2B59TaQTG9hx6v%2FC33yF62Na7gI7auYJsR%2BHzy1iqE0PGAz6TxsLOy6p2RRiuZ%2BZMYAGVCzCd3eT%2FEwZTbJVf2WKqkloyS1ucgQDk1gc4o9r%2BtOK05Lp8UmYH0Lc%2FqvPDVcWOMS38t3I0SBjPjM3A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/config.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aFO1ri7b49f8ypxktMGRu5N8KOKNbziyLqleUH09MPuA9PAYZ%2FUEkzNPS3oRL0qGvnykBS1HQtgfvNCRTijfwD2pBGklHVDw8PW2AdH3Vxwf1m6Z96Qh%2FZVyaFAMruifaFo1jxASWgELM6qrkGn856Aisqe%2B6dpUJgxU7vtPajwRGPMhw4jQEsZyN4xP%2FTpi7T%2B59TaQTG9hx6v%2FC33yF62Na7gI7auYJsR%2BHzy1iqE0PGAz6TxsLOy6p2RRiuZ%2BZMYAGVCzCd3eT%2FEwZTbJVf2WKqkloyS1ucgQDk1gc4o9r%2BtOK05Lp8UmYH0Lc%2FqvPDVcWOMS38t3I0SBjPjM3A%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:49,591 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:48:49,591 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:49,621 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/requirements.txt?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L0an32z%2FB0wLz2JFrECP4BBFcscjiTu1R%2FzsFG4dnijS3JHmjS%2FNQ49Cs5BjPgsrYnV8ZjPX4eN7TLCL%2FIyLEmyMjPXYfUvKj%2FSlEAK54p3ibrnqkg%2FVw9urQ8Hi06%2B0b5nfvkq2fqboltJgPRAAlveUmdz7d%2BI%2F9ARZqf6uhVSCPnWJcMY%2FqKb5fOcrrfzyoUQEwhTGFGuB3HLBBP%2F5%2FGULu2vTvqlcJyGJQKglRZnPAmdaWT3R9IqLs5F96EVEz0vWTeBVOkjooUYLHMeXtE1iKNucouCWLfDjOhwCqLLIGjsNUoCDhqvcuT5hTDPjHFIw3uQdtNInn4o53wFXOQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/requirements.txt?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L0an32z%2FB0wLz2JFrECP4BBFcscjiTu1R%2FzsFG4dnijS3JHmjS%2FNQ49Cs5BjPgsrYnV8ZjPX4eN7TLCL%2FIyLEmyMjPXYfUvKj%2FSlEAK54p3ibrnqkg%2FVw9urQ8Hi06%2B0b5nfvkq2fqboltJgPRAAlveUmdz7d%2BI%2F9ARZqf6uhVSCPnWJcMY%2FqKb5fOcrrfzyoUQEwhTGFGuB3HLBBP%2F5%2FGULu2vTvqlcJyGJQKglRZnPAmdaWT3R9IqLs5F96EVEz0vWTeBVOkjooUYLHMeXtE1iKNucouCWLfDjOhwCqLLIGjsNUoCDhqvcuT5hTDPjHFIw3uQdtNInn4o53wFXOQ%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:49,621 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:48:49,621 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:49,656 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-summary.json?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lv8tEb7iA%2BH803MBGYiNAow1meuL%2FLCrMLeKqPBNz%2BF%2FYs4n2%2F775TA2f77UwwabErQ1pSL1JW%2FZ4LTtOLmy6wX4rLeSq0QUYqfHsexktkCEZJem9Sty%2BaUF4X0zgq0T7DJ8OpEGagmQXFSvYEg7gWKPYjrrLyM2m4cGoX41YP7N5O0PMz%2BN2G8WP9Y7lSg%2FfKDFQCUeVxjOTVXjdn2XPEj2Xc0yd5vPH9rn4HUH0CUWa1QPDQP5HN9qFnkQOGi%2FX%2BzjGte9Rpoe8TvymKHpVW3a2ZA00NFnCePxHTDKGC%2F9CNxMnOw9PbEnmmWEVWDEy9vioG5NfRBeLfAExSG0pw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-summary.json?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lv8tEb7iA%2BH803MBGYiNAow1meuL%2FLCrMLeKqPBNz%2BF%2FYs4n2%2F775TA2f77UwwabErQ1pSL1JW%2FZ4LTtOLmy6wX4rLeSq0QUYqfHsexktkCEZJem9Sty%2BaUF4X0zgq0T7DJ8OpEGagmQXFSvYEg7gWKPYjrrLyM2m4cGoX41YP7N5O0PMz%2BN2G8WP9Y7lSg%2FfKDFQCUeVxjOTVXjdn2XPEj2Xc0yd5vPH9rn4HUH0CUWa1QPDQP5HN9qFnkQOGi%2FX%2BzjGte9Rpoe8TvymKHpVW3a2ZA00NFnCePxHTDKGC%2F9CNxMnOw9PbEnmmWEVWDEy9vioG5NfRBeLfAExSG0pw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:49,657 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '122'}
2024-07-17 10:48:49,657 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:50,292 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:50,293 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:48:50,788 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/conda-environment.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WX8ySpKkxR7NeIRfOJE90zRpnaGZVqbP0aB1wpn%2FSg1qhNalNT4xoQ149%2BajNtMOqdN6yHlY2O0ioHbxw5Mml1S4fGOLM%2BnxGMrnVte6KhIBkSwxz9HJuSrrPDkxwTJEaDZ1E7nVAeHNbkM9%2BMxQE9duRXD9hHC8Ci6GOyzrC%2FjYFoduP3eZ3yp7aTCg%2Fi5NMMA%2BdeS6QFudN%2BXo2XmapJUzvABhqsMULVa9DmfR6ByVpImzCAfh4U0o24RiLCgKQc9uZzg8sSzcj7OYsPPq12hJbyADemZzEwu54nUXJR5HIv8E2dxrXlPwwyR01K7%2Fn7Uu6S1Epc9gm7A42dP%2F2g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/conda-environment.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WX8ySpKkxR7NeIRfOJE90zRpnaGZVqbP0aB1wpn%2FSg1qhNalNT4xoQ149%2BajNtMOqdN6yHlY2O0ioHbxw5Mml1S4fGOLM%2BnxGMrnVte6KhIBkSwxz9HJuSrrPDkxwTJEaDZ1E7nVAeHNbkM9%2BMxQE9duRXD9hHC8Ci6GOyzrC%2FjYFoduP3eZ3yp7aTCg%2Fi5NMMA%2BdeS6QFudN%2BXo2XmapJUzvABhqsMULVa9DmfR6ByVpImzCAfh4U0o24RiLCgKQc9uZzg8sSzcj7OYsPPq12hJbyADemZzEwu54nUXJR5HIv8E2dxrXlPwwyR01K7%2Fn7Uu6S1Epc9gm7A42dP%2F2g%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:50,788 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:48:50,788 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:50,867 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/config.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aFO1ri7b49f8ypxktMGRu5N8KOKNbziyLqleUH09MPuA9PAYZ%2FUEkzNPS3oRL0qGvnykBS1HQtgfvNCRTijfwD2pBGklHVDw8PW2AdH3Vxwf1m6Z96Qh%2FZVyaFAMruifaFo1jxASWgELM6qrkGn856Aisqe%2B6dpUJgxU7vtPajwRGPMhw4jQEsZyN4xP%2FTpi7T%2B59TaQTG9hx6v%2FC33yF62Na7gI7auYJsR%2BHzy1iqE0PGAz6TxsLOy6p2RRiuZ%2BZMYAGVCzCd3eT%2FEwZTbJVf2WKqkloyS1ucgQDk1gc4o9r%2BtOK05Lp8UmYH0Lc%2FqvPDVcWOMS38t3I0SBjPjM3A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/config.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aFO1ri7b49f8ypxktMGRu5N8KOKNbziyLqleUH09MPuA9PAYZ%2FUEkzNPS3oRL0qGvnykBS1HQtgfvNCRTijfwD2pBGklHVDw8PW2AdH3Vxwf1m6Z96Qh%2FZVyaFAMruifaFo1jxASWgELM6qrkGn856Aisqe%2B6dpUJgxU7vtPajwRGPMhw4jQEsZyN4xP%2FTpi7T%2B59TaQTG9hx6v%2FC33yF62Na7gI7auYJsR%2BHzy1iqE0PGAz6TxsLOy6p2RRiuZ%2BZMYAGVCzCd3eT%2FEwZTbJVf2WKqkloyS1ucgQDk1gc4o9r%2BtOK05Lp8UmYH0Lc%2FqvPDVcWOMS38t3I0SBjPjM3A%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:50,867 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:48:50,867 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:50,885 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/requirements.txt?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L0an32z%2FB0wLz2JFrECP4BBFcscjiTu1R%2FzsFG4dnijS3JHmjS%2FNQ49Cs5BjPgsrYnV8ZjPX4eN7TLCL%2FIyLEmyMjPXYfUvKj%2FSlEAK54p3ibrnqkg%2FVw9urQ8Hi06%2B0b5nfvkq2fqboltJgPRAAlveUmdz7d%2BI%2F9ARZqf6uhVSCPnWJcMY%2FqKb5fOcrrfzyoUQEwhTGFGuB3HLBBP%2F5%2FGULu2vTvqlcJyGJQKglRZnPAmdaWT3R9IqLs5F96EVEz0vWTeBVOkjooUYLHMeXtE1iKNucouCWLfDjOhwCqLLIGjsNUoCDhqvcuT5hTDPjHFIw3uQdtNInn4o53wFXOQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/requirements.txt?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L0an32z%2FB0wLz2JFrECP4BBFcscjiTu1R%2FzsFG4dnijS3JHmjS%2FNQ49Cs5BjPgsrYnV8ZjPX4eN7TLCL%2FIyLEmyMjPXYfUvKj%2FSlEAK54p3ibrnqkg%2FVw9urQ8Hi06%2B0b5nfvkq2fqboltJgPRAAlveUmdz7d%2BI%2F9ARZqf6uhVSCPnWJcMY%2FqKb5fOcrrfzyoUQEwhTGFGuB3HLBBP%2F5%2FGULu2vTvqlcJyGJQKglRZnPAmdaWT3R9IqLs5F96EVEz0vWTeBVOkjooUYLHMeXtE1iKNucouCWLfDjOhwCqLLIGjsNUoCDhqvcuT5hTDPjHFIw3uQdtNInn4o53wFXOQ%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:50,885 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:48:50,885 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:50,941 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-summary.json?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lv8tEb7iA%2BH803MBGYiNAow1meuL%2FLCrMLeKqPBNz%2BF%2FYs4n2%2F775TA2f77UwwabErQ1pSL1JW%2FZ4LTtOLmy6wX4rLeSq0QUYqfHsexktkCEZJem9Sty%2BaUF4X0zgq0T7DJ8OpEGagmQXFSvYEg7gWKPYjrrLyM2m4cGoX41YP7N5O0PMz%2BN2G8WP9Y7lSg%2FfKDFQCUeVxjOTVXjdn2XPEj2Xc0yd5vPH9rn4HUH0CUWa1QPDQP5HN9qFnkQOGi%2FX%2BzjGte9Rpoe8TvymKHpVW3a2ZA00NFnCePxHTDKGC%2F9CNxMnOw9PbEnmmWEVWDEy9vioG5NfRBeLfAExSG0pw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-summary.json?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lv8tEb7iA%2BH803MBGYiNAow1meuL%2FLCrMLeKqPBNz%2BF%2FYs4n2%2F775TA2f77UwwabErQ1pSL1JW%2FZ4LTtOLmy6wX4rLeSq0QUYqfHsexktkCEZJem9Sty%2BaUF4X0zgq0T7DJ8OpEGagmQXFSvYEg7gWKPYjrrLyM2m4cGoX41YP7N5O0PMz%2BN2G8WP9Y7lSg%2FfKDFQCUeVxjOTVXjdn2XPEj2Xc0yd5vPH9rn4HUH0CUWa1QPDQP5HN9qFnkQOGi%2FX%2BzjGte9Rpoe8TvymKHpVW3a2ZA00NFnCePxHTDKGC%2F9CNxMnOw9PbEnmmWEVWDEy9vioG5NfRBeLfAExSG0pw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:50,941 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '122'}
2024-07-17 10:48:50,941 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:51,305 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:51,306 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:48:51,559 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-metadata.json?Expires=1721314127&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NGG0rTtVplkZfiGLvfFKD7cUeLbfqz%2BGCzDKiaAprYzhNBM6%2B8CFULGjRYmPlAtEQoUc%2BRIkmFkRjfPIK%2FSjlSq8eJgN1OiNDGaPwoRnjOsj20Ke%2Bhe3m%2BtrtqcrI%2B8p%2B7vCwVUBPuxSDtGt8DAEBHbwnIUrJngjkO0KJ4bWQZnRFX3jADnmvkzoNsMyZN9tYvhqq5GPdUuYMu1PJVNdaZmwFtbuxXZnaWEhStvhjWMiRw6ysql7y0zChU0N4WTG6bspmoutMuwHBjjM71Pu2Hyslc%2FCdSWB%2BmC0hn7GTK0c9cLfjkIb1DPxk7xGmXsh4SK76QqEcpbpL6B6iQDLJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-metadata.json?Expires=1721314127&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NGG0rTtVplkZfiGLvfFKD7cUeLbfqz%2BGCzDKiaAprYzhNBM6%2B8CFULGjRYmPlAtEQoUc%2BRIkmFkRjfPIK%2FSjlSq8eJgN1OiNDGaPwoRnjOsj20Ke%2Bhe3m%2BtrtqcrI%2B8p%2B7vCwVUBPuxSDtGt8DAEBHbwnIUrJngjkO0KJ4bWQZnRFX3jADnmvkzoNsMyZN9tYvhqq5GPdUuYMu1PJVNdaZmwFtbuxXZnaWEhStvhjWMiRw6ysql7y0zChU0N4WTG6bspmoutMuwHBjjM71Pu2Hyslc%2FCdSWB%2BmC0hn7GTK0c9cLfjkIb1DPxk7xGmXsh4SK76QqEcpbpL6B6iQDLJw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:51,559 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:48:51,559 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:52,308 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:52,308 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:48:53,262 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/conda-environment.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WX8ySpKkxR7NeIRfOJE90zRpnaGZVqbP0aB1wpn%2FSg1qhNalNT4xoQ149%2BajNtMOqdN6yHlY2O0ioHbxw5Mml1S4fGOLM%2BnxGMrnVte6KhIBkSwxz9HJuSrrPDkxwTJEaDZ1E7nVAeHNbkM9%2BMxQE9duRXD9hHC8Ci6GOyzrC%2FjYFoduP3eZ3yp7aTCg%2Fi5NMMA%2BdeS6QFudN%2BXo2XmapJUzvABhqsMULVa9DmfR6ByVpImzCAfh4U0o24RiLCgKQc9uZzg8sSzcj7OYsPPq12hJbyADemZzEwu54nUXJR5HIv8E2dxrXlPwwyR01K7%2Fn7Uu6S1Epc9gm7A42dP%2F2g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/conda-environment.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WX8ySpKkxR7NeIRfOJE90zRpnaGZVqbP0aB1wpn%2FSg1qhNalNT4xoQ149%2BajNtMOqdN6yHlY2O0ioHbxw5Mml1S4fGOLM%2BnxGMrnVte6KhIBkSwxz9HJuSrrPDkxwTJEaDZ1E7nVAeHNbkM9%2BMxQE9duRXD9hHC8Ci6GOyzrC%2FjYFoduP3eZ3yp7aTCg%2Fi5NMMA%2BdeS6QFudN%2BXo2XmapJUzvABhqsMULVa9DmfR6ByVpImzCAfh4U0o24RiLCgKQc9uZzg8sSzcj7OYsPPq12hJbyADemZzEwu54nUXJR5HIv8E2dxrXlPwwyR01K7%2Fn7Uu6S1Epc9gm7A42dP%2F2g%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:53,262 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:48:53,262 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:53,267 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/config.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aFO1ri7b49f8ypxktMGRu5N8KOKNbziyLqleUH09MPuA9PAYZ%2FUEkzNPS3oRL0qGvnykBS1HQtgfvNCRTijfwD2pBGklHVDw8PW2AdH3Vxwf1m6Z96Qh%2FZVyaFAMruifaFo1jxASWgELM6qrkGn856Aisqe%2B6dpUJgxU7vtPajwRGPMhw4jQEsZyN4xP%2FTpi7T%2B59TaQTG9hx6v%2FC33yF62Na7gI7auYJsR%2BHzy1iqE0PGAz6TxsLOy6p2RRiuZ%2BZMYAGVCzCd3eT%2FEwZTbJVf2WKqkloyS1ucgQDk1gc4o9r%2BtOK05Lp8UmYH0Lc%2FqvPDVcWOMS38t3I0SBjPjM3A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/config.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aFO1ri7b49f8ypxktMGRu5N8KOKNbziyLqleUH09MPuA9PAYZ%2FUEkzNPS3oRL0qGvnykBS1HQtgfvNCRTijfwD2pBGklHVDw8PW2AdH3Vxwf1m6Z96Qh%2FZVyaFAMruifaFo1jxASWgELM6qrkGn856Aisqe%2B6dpUJgxU7vtPajwRGPMhw4jQEsZyN4xP%2FTpi7T%2B59TaQTG9hx6v%2FC33yF62Na7gI7auYJsR%2BHzy1iqE0PGAz6TxsLOy6p2RRiuZ%2BZMYAGVCzCd3eT%2FEwZTbJVf2WKqkloyS1ucgQDk1gc4o9r%2BtOK05Lp8UmYH0Lc%2FqvPDVcWOMS38t3I0SBjPjM3A%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:53,267 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:48:53,267 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:53,271 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-summary.json?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lv8tEb7iA%2BH803MBGYiNAow1meuL%2FLCrMLeKqPBNz%2BF%2FYs4n2%2F775TA2f77UwwabErQ1pSL1JW%2FZ4LTtOLmy6wX4rLeSq0QUYqfHsexktkCEZJem9Sty%2BaUF4X0zgq0T7DJ8OpEGagmQXFSvYEg7gWKPYjrrLyM2m4cGoX41YP7N5O0PMz%2BN2G8WP9Y7lSg%2FfKDFQCUeVxjOTVXjdn2XPEj2Xc0yd5vPH9rn4HUH0CUWa1QPDQP5HN9qFnkQOGi%2FX%2BzjGte9Rpoe8TvymKHpVW3a2ZA00NFnCePxHTDKGC%2F9CNxMnOw9PbEnmmWEVWDEy9vioG5NfRBeLfAExSG0pw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-summary.json?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lv8tEb7iA%2BH803MBGYiNAow1meuL%2FLCrMLeKqPBNz%2BF%2FYs4n2%2F775TA2f77UwwabErQ1pSL1JW%2FZ4LTtOLmy6wX4rLeSq0QUYqfHsexktkCEZJem9Sty%2BaUF4X0zgq0T7DJ8OpEGagmQXFSvYEg7gWKPYjrrLyM2m4cGoX41YP7N5O0PMz%2BN2G8WP9Y7lSg%2FfKDFQCUeVxjOTVXjdn2XPEj2Xc0yd5vPH9rn4HUH0CUWa1QPDQP5HN9qFnkQOGi%2FX%2BzjGte9Rpoe8TvymKHpVW3a2ZA00NFnCePxHTDKGC%2F9CNxMnOw9PbEnmmWEVWDEy9vioG5NfRBeLfAExSG0pw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:53,272 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '122'}
2024-07-17 10:48:53,272 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:53,317 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:53,317 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:48:53,344 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/requirements.txt?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L0an32z%2FB0wLz2JFrECP4BBFcscjiTu1R%2FzsFG4dnijS3JHmjS%2FNQ49Cs5BjPgsrYnV8ZjPX4eN7TLCL%2FIyLEmyMjPXYfUvKj%2FSlEAK54p3ibrnqkg%2FVw9urQ8Hi06%2B0b5nfvkq2fqboltJgPRAAlveUmdz7d%2BI%2F9ARZqf6uhVSCPnWJcMY%2FqKb5fOcrrfzyoUQEwhTGFGuB3HLBBP%2F5%2FGULu2vTvqlcJyGJQKglRZnPAmdaWT3R9IqLs5F96EVEz0vWTeBVOkjooUYLHMeXtE1iKNucouCWLfDjOhwCqLLIGjsNUoCDhqvcuT5hTDPjHFIw3uQdtNInn4o53wFXOQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/requirements.txt?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L0an32z%2FB0wLz2JFrECP4BBFcscjiTu1R%2FzsFG4dnijS3JHmjS%2FNQ49Cs5BjPgsrYnV8ZjPX4eN7TLCL%2FIyLEmyMjPXYfUvKj%2FSlEAK54p3ibrnqkg%2FVw9urQ8Hi06%2B0b5nfvkq2fqboltJgPRAAlveUmdz7d%2BI%2F9ARZqf6uhVSCPnWJcMY%2FqKb5fOcrrfzyoUQEwhTGFGuB3HLBBP%2F5%2FGULu2vTvqlcJyGJQKglRZnPAmdaWT3R9IqLs5F96EVEz0vWTeBVOkjooUYLHMeXtE1iKNucouCWLfDjOhwCqLLIGjsNUoCDhqvcuT5hTDPjHFIw3uQdtNInn4o53wFXOQ%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:53,344 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:48:53,344 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:54,332 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:54,333 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:48:55,335 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:55,336 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:48:55,749 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-metadata.json?Expires=1721314127&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NGG0rTtVplkZfiGLvfFKD7cUeLbfqz%2BGCzDKiaAprYzhNBM6%2B8CFULGjRYmPlAtEQoUc%2BRIkmFkRjfPIK%2FSjlSq8eJgN1OiNDGaPwoRnjOsj20Ke%2Bhe3m%2BtrtqcrI%2B8p%2B7vCwVUBPuxSDtGt8DAEBHbwnIUrJngjkO0KJ4bWQZnRFX3jADnmvkzoNsMyZN9tYvhqq5GPdUuYMu1PJVNdaZmwFtbuxXZnaWEhStvhjWMiRw6ysql7y0zChU0N4WTG6bspmoutMuwHBjjM71Pu2Hyslc%2FCdSWB%2BmC0hn7GTK0c9cLfjkIb1DPxk7xGmXsh4SK76QqEcpbpL6B6iQDLJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-metadata.json?Expires=1721314127&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NGG0rTtVplkZfiGLvfFKD7cUeLbfqz%2BGCzDKiaAprYzhNBM6%2B8CFULGjRYmPlAtEQoUc%2BRIkmFkRjfPIK%2FSjlSq8eJgN1OiNDGaPwoRnjOsj20Ke%2Bhe3m%2BtrtqcrI%2B8p%2B7vCwVUBPuxSDtGt8DAEBHbwnIUrJngjkO0KJ4bWQZnRFX3jADnmvkzoNsMyZN9tYvhqq5GPdUuYMu1PJVNdaZmwFtbuxXZnaWEhStvhjWMiRw6ysql7y0zChU0N4WTG6bspmoutMuwHBjjM71Pu2Hyslc%2FCdSWB%2BmC0hn7GTK0c9cLfjkIb1DPxk7xGmXsh4SK76QqEcpbpL6B6iQDLJw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:55,749 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:48:55,749 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:56,342 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: status_report
2024-07-17 10:48:56,342 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:56,343 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:48:57,350 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:57,350 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:48:57,656 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/conda-environment.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WX8ySpKkxR7NeIRfOJE90zRpnaGZVqbP0aB1wpn%2FSg1qhNalNT4xoQ149%2BajNtMOqdN6yHlY2O0ioHbxw5Mml1S4fGOLM%2BnxGMrnVte6KhIBkSwxz9HJuSrrPDkxwTJEaDZ1E7nVAeHNbkM9%2BMxQE9duRXD9hHC8Ci6GOyzrC%2FjYFoduP3eZ3yp7aTCg%2Fi5NMMA%2BdeS6QFudN%2BXo2XmapJUzvABhqsMULVa9DmfR6ByVpImzCAfh4U0o24RiLCgKQc9uZzg8sSzcj7OYsPPq12hJbyADemZzEwu54nUXJR5HIv8E2dxrXlPwwyR01K7%2Fn7Uu6S1Epc9gm7A42dP%2F2g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/conda-environment.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WX8ySpKkxR7NeIRfOJE90zRpnaGZVqbP0aB1wpn%2FSg1qhNalNT4xoQ149%2BajNtMOqdN6yHlY2O0ioHbxw5Mml1S4fGOLM%2BnxGMrnVte6KhIBkSwxz9HJuSrrPDkxwTJEaDZ1E7nVAeHNbkM9%2BMxQE9duRXD9hHC8Ci6GOyzrC%2FjYFoduP3eZ3yp7aTCg%2Fi5NMMA%2BdeS6QFudN%2BXo2XmapJUzvABhqsMULVa9DmfR6ByVpImzCAfh4U0o24RiLCgKQc9uZzg8sSzcj7OYsPPq12hJbyADemZzEwu54nUXJR5HIv8E2dxrXlPwwyR01K7%2Fn7Uu6S1Epc9gm7A42dP%2F2g%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:57,656 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:48:57,656 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:57,783 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/config.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aFO1ri7b49f8ypxktMGRu5N8KOKNbziyLqleUH09MPuA9PAYZ%2FUEkzNPS3oRL0qGvnykBS1HQtgfvNCRTijfwD2pBGklHVDw8PW2AdH3Vxwf1m6Z96Qh%2FZVyaFAMruifaFo1jxASWgELM6qrkGn856Aisqe%2B6dpUJgxU7vtPajwRGPMhw4jQEsZyN4xP%2FTpi7T%2B59TaQTG9hx6v%2FC33yF62Na7gI7auYJsR%2BHzy1iqE0PGAz6TxsLOy6p2RRiuZ%2BZMYAGVCzCd3eT%2FEwZTbJVf2WKqkloyS1ucgQDk1gc4o9r%2BtOK05Lp8UmYH0Lc%2FqvPDVcWOMS38t3I0SBjPjM3A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/config.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aFO1ri7b49f8ypxktMGRu5N8KOKNbziyLqleUH09MPuA9PAYZ%2FUEkzNPS3oRL0qGvnykBS1HQtgfvNCRTijfwD2pBGklHVDw8PW2AdH3Vxwf1m6Z96Qh%2FZVyaFAMruifaFo1jxASWgELM6qrkGn856Aisqe%2B6dpUJgxU7vtPajwRGPMhw4jQEsZyN4xP%2FTpi7T%2B59TaQTG9hx6v%2FC33yF62Na7gI7auYJsR%2BHzy1iqE0PGAz6TxsLOy6p2RRiuZ%2BZMYAGVCzCd3eT%2FEwZTbJVf2WKqkloyS1ucgQDk1gc4o9r%2BtOK05Lp8UmYH0Lc%2FqvPDVcWOMS38t3I0SBjPjM3A%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:57,783 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:48:57,783 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:57,942 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-summary.json?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lv8tEb7iA%2BH803MBGYiNAow1meuL%2FLCrMLeKqPBNz%2BF%2FYs4n2%2F775TA2f77UwwabErQ1pSL1JW%2FZ4LTtOLmy6wX4rLeSq0QUYqfHsexktkCEZJem9Sty%2BaUF4X0zgq0T7DJ8OpEGagmQXFSvYEg7gWKPYjrrLyM2m4cGoX41YP7N5O0PMz%2BN2G8WP9Y7lSg%2FfKDFQCUeVxjOTVXjdn2XPEj2Xc0yd5vPH9rn4HUH0CUWa1QPDQP5HN9qFnkQOGi%2FX%2BzjGte9Rpoe8TvymKHpVW3a2ZA00NFnCePxHTDKGC%2F9CNxMnOw9PbEnmmWEVWDEy9vioG5NfRBeLfAExSG0pw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-summary.json?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lv8tEb7iA%2BH803MBGYiNAow1meuL%2FLCrMLeKqPBNz%2BF%2FYs4n2%2F775TA2f77UwwabErQ1pSL1JW%2FZ4LTtOLmy6wX4rLeSq0QUYqfHsexktkCEZJem9Sty%2BaUF4X0zgq0T7DJ8OpEGagmQXFSvYEg7gWKPYjrrLyM2m4cGoX41YP7N5O0PMz%2BN2G8WP9Y7lSg%2FfKDFQCUeVxjOTVXjdn2XPEj2Xc0yd5vPH9rn4HUH0CUWa1QPDQP5HN9qFnkQOGi%2FX%2BzjGte9Rpoe8TvymKHpVW3a2ZA00NFnCePxHTDKGC%2F9CNxMnOw9PbEnmmWEVWDEy9vioG5NfRBeLfAExSG0pw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:57,942 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '122'}
2024-07-17 10:48:57,942 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:58,038 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/requirements.txt?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L0an32z%2FB0wLz2JFrECP4BBFcscjiTu1R%2FzsFG4dnijS3JHmjS%2FNQ49Cs5BjPgsrYnV8ZjPX4eN7TLCL%2FIyLEmyMjPXYfUvKj%2FSlEAK54p3ibrnqkg%2FVw9urQ8Hi06%2B0b5nfvkq2fqboltJgPRAAlveUmdz7d%2BI%2F9ARZqf6uhVSCPnWJcMY%2FqKb5fOcrrfzyoUQEwhTGFGuB3HLBBP%2F5%2FGULu2vTvqlcJyGJQKglRZnPAmdaWT3R9IqLs5F96EVEz0vWTeBVOkjooUYLHMeXtE1iKNucouCWLfDjOhwCqLLIGjsNUoCDhqvcuT5hTDPjHFIw3uQdtNInn4o53wFXOQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/requirements.txt?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L0an32z%2FB0wLz2JFrECP4BBFcscjiTu1R%2FzsFG4dnijS3JHmjS%2FNQ49Cs5BjPgsrYnV8ZjPX4eN7TLCL%2FIyLEmyMjPXYfUvKj%2FSlEAK54p3ibrnqkg%2FVw9urQ8Hi06%2B0b5nfvkq2fqboltJgPRAAlveUmdz7d%2BI%2F9ARZqf6uhVSCPnWJcMY%2FqKb5fOcrrfzyoUQEwhTGFGuB3HLBBP%2F5%2FGULu2vTvqlcJyGJQKglRZnPAmdaWT3R9IqLs5F96EVEz0vWTeBVOkjooUYLHMeXtE1iKNucouCWLfDjOhwCqLLIGjsNUoCDhqvcuT5hTDPjHFIw3uQdtNInn4o53wFXOQ%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:48:58,038 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:48:58,038 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:48:58,352 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:58,352 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:48:59,362 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:48:59,363 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:00,375 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:00,376 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:01,383 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: status_report
2024-07-17 10:49:01,384 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:01,384 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:02,393 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:02,393 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:03,397 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:03,397 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:04,398 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:04,398 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:05,199 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-metadata.json?Expires=1721314127&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NGG0rTtVplkZfiGLvfFKD7cUeLbfqz%2BGCzDKiaAprYzhNBM6%2B8CFULGjRYmPlAtEQoUc%2BRIkmFkRjfPIK%2FSjlSq8eJgN1OiNDGaPwoRnjOsj20Ke%2Bhe3m%2BtrtqcrI%2B8p%2B7vCwVUBPuxSDtGt8DAEBHbwnIUrJngjkO0KJ4bWQZnRFX3jADnmvkzoNsMyZN9tYvhqq5GPdUuYMu1PJVNdaZmwFtbuxXZnaWEhStvhjWMiRw6ysql7y0zChU0N4WTG6bspmoutMuwHBjjM71Pu2Hyslc%2FCdSWB%2BmC0hn7GTK0c9cLfjkIb1DPxk7xGmXsh4SK76QqEcpbpL6B6iQDLJw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-metadata.json?Expires=1721314127&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NGG0rTtVplkZfiGLvfFKD7cUeLbfqz%2BGCzDKiaAprYzhNBM6%2B8CFULGjRYmPlAtEQoUc%2BRIkmFkRjfPIK%2FSjlSq8eJgN1OiNDGaPwoRnjOsj20Ke%2Bhe3m%2BtrtqcrI%2B8p%2B7vCwVUBPuxSDtGt8DAEBHbwnIUrJngjkO0KJ4bWQZnRFX3jADnmvkzoNsMyZN9tYvhqq5GPdUuYMu1PJVNdaZmwFtbuxXZnaWEhStvhjWMiRw6ysql7y0zChU0N4WTG6bspmoutMuwHBjjM71Pu2Hyslc%2FCdSWB%2BmC0hn7GTK0c9cLfjkIb1DPxk7xGmXsh4SK76QqEcpbpL6B6iQDLJw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:05,199 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1203'}
2024-07-17 10:49:05,199 ERROR   wandb-upload_0:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:05,399 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:05,399 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:06,405 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: status_report
2024-07-17 10:49:06,405 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:06,405 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:06,721 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/requirements.txt?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L0an32z%2FB0wLz2JFrECP4BBFcscjiTu1R%2FzsFG4dnijS3JHmjS%2FNQ49Cs5BjPgsrYnV8ZjPX4eN7TLCL%2FIyLEmyMjPXYfUvKj%2FSlEAK54p3ibrnqkg%2FVw9urQ8Hi06%2B0b5nfvkq2fqboltJgPRAAlveUmdz7d%2BI%2F9ARZqf6uhVSCPnWJcMY%2FqKb5fOcrrfzyoUQEwhTGFGuB3HLBBP%2F5%2FGULu2vTvqlcJyGJQKglRZnPAmdaWT3R9IqLs5F96EVEz0vWTeBVOkjooUYLHMeXtE1iKNucouCWLfDjOhwCqLLIGjsNUoCDhqvcuT5hTDPjHFIw3uQdtNInn4o53wFXOQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/requirements.txt?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=L0an32z%2FB0wLz2JFrECP4BBFcscjiTu1R%2FzsFG4dnijS3JHmjS%2FNQ49Cs5BjPgsrYnV8ZjPX4eN7TLCL%2FIyLEmyMjPXYfUvKj%2FSlEAK54p3ibrnqkg%2FVw9urQ8Hi06%2B0b5nfvkq2fqboltJgPRAAlveUmdz7d%2BI%2F9ARZqf6uhVSCPnWJcMY%2FqKb5fOcrrfzyoUQEwhTGFGuB3HLBBP%2F5%2FGULu2vTvqlcJyGJQKglRZnPAmdaWT3R9IqLs5F96EVEz0vWTeBVOkjooUYLHMeXtE1iKNucouCWLfDjOhwCqLLIGjsNUoCDhqvcuT5hTDPjHFIw3uQdtNInn4o53wFXOQ%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:06,721 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '709'}
2024-07-17 10:49:06,721 ERROR   wandb-upload_3:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:06,998 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-summary.json?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lv8tEb7iA%2BH803MBGYiNAow1meuL%2FLCrMLeKqPBNz%2BF%2FYs4n2%2F775TA2f77UwwabErQ1pSL1JW%2FZ4LTtOLmy6wX4rLeSq0QUYqfHsexktkCEZJem9Sty%2BaUF4X0zgq0T7DJ8OpEGagmQXFSvYEg7gWKPYjrrLyM2m4cGoX41YP7N5O0PMz%2BN2G8WP9Y7lSg%2FfKDFQCUeVxjOTVXjdn2XPEj2Xc0yd5vPH9rn4HUH0CUWa1QPDQP5HN9qFnkQOGi%2FX%2BzjGte9Rpoe8TvymKHpVW3a2ZA00NFnCePxHTDKGC%2F9CNxMnOw9PbEnmmWEVWDEy9vioG5NfRBeLfAExSG0pw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/wandb-summary.json?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=lv8tEb7iA%2BH803MBGYiNAow1meuL%2FLCrMLeKqPBNz%2BF%2FYs4n2%2F775TA2f77UwwabErQ1pSL1JW%2FZ4LTtOLmy6wX4rLeSq0QUYqfHsexktkCEZJem9Sty%2BaUF4X0zgq0T7DJ8OpEGagmQXFSvYEg7gWKPYjrrLyM2m4cGoX41YP7N5O0PMz%2BN2G8WP9Y7lSg%2FfKDFQCUeVxjOTVXjdn2XPEj2Xc0yd5vPH9rn4HUH0CUWa1QPDQP5HN9qFnkQOGi%2FX%2BzjGte9Rpoe8TvymKHpVW3a2ZA00NFnCePxHTDKGC%2F9CNxMnOw9PbEnmmWEVWDEy9vioG5NfRBeLfAExSG0pw%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:06,999 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '122'}
2024-07-17 10:49:06,999 ERROR   wandb-upload_4:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:06,999 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/conda-environment.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WX8ySpKkxR7NeIRfOJE90zRpnaGZVqbP0aB1wpn%2FSg1qhNalNT4xoQ149%2BajNtMOqdN6yHlY2O0ioHbxw5Mml1S4fGOLM%2BnxGMrnVte6KhIBkSwxz9HJuSrrPDkxwTJEaDZ1E7nVAeHNbkM9%2BMxQE9duRXD9hHC8Ci6GOyzrC%2FjYFoduP3eZ3yp7aTCg%2Fi5NMMA%2BdeS6QFudN%2BXo2XmapJUzvABhqsMULVa9DmfR6ByVpImzCAfh4U0o24RiLCgKQc9uZzg8sSzcj7OYsPPq12hJbyADemZzEwu54nUXJR5HIv8E2dxrXlPwwyR01K7%2Fn7Uu6S1Epc9gm7A42dP%2F2g%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/conda-environment.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=WX8ySpKkxR7NeIRfOJE90zRpnaGZVqbP0aB1wpn%2FSg1qhNalNT4xoQ149%2BajNtMOqdN6yHlY2O0ioHbxw5Mml1S4fGOLM%2BnxGMrnVte6KhIBkSwxz9HJuSrrPDkxwTJEaDZ1E7nVAeHNbkM9%2BMxQE9duRXD9hHC8Ci6GOyzrC%2FjYFoduP3eZ3yp7aTCg%2Fi5NMMA%2BdeS6QFudN%2BXo2XmapJUzvABhqsMULVa9DmfR6ByVpImzCAfh4U0o24RiLCgKQc9uZzg8sSzcj7OYsPPq12hJbyADemZzEwu54nUXJR5HIv8E2dxrXlPwwyR01K7%2Fn7Uu6S1Epc9gm7A42dP%2F2g%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:06,999 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1201'}
2024-07-17 10:49:06,999 ERROR   wandb-upload_1:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:07,406 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:07,406 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:07,408 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2887] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/rasool/test_project/ishnh8z9/config.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aFO1ri7b49f8ypxktMGRu5N8KOKNbziyLqleUH09MPuA9PAYZ%2FUEkzNPS3oRL0qGvnykBS1HQtgfvNCRTijfwD2pBGklHVDw8PW2AdH3Vxwf1m6Z96Qh%2FZVyaFAMruifaFo1jxASWgELM6qrkGn856Aisqe%2B6dpUJgxU7vtPajwRGPMhw4jQEsZyN4xP%2FTpi7T%2B59TaQTG9hx6v%2FC33yF62Na7gI7auYJsR%2BHzy1iqE0PGAz6TxsLOy6p2RRiuZ%2BZMYAGVCzCd3eT%2FEwZTbJVf2WKqkloyS1ucgQDk1gc4o9r%2BtOK05Lp8UmYH0Lc%2FqvPDVcWOMS38t3I0SBjPjM3A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/rasool/test_project/ishnh8z9/config.yaml?Expires=1721314129&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=aFO1ri7b49f8ypxktMGRu5N8KOKNbziyLqleUH09MPuA9PAYZ%2FUEkzNPS3oRL0qGvnykBS1HQtgfvNCRTijfwD2pBGklHVDw8PW2AdH3Vxwf1m6Z96Qh%2FZVyaFAMruifaFo1jxASWgELM6qrkGn856Aisqe%2B6dpUJgxU7vtPajwRGPMhw4jQEsZyN4xP%2FTpi7T%2B59TaQTG9hx6v%2FC33yF62Na7gI7auYJsR%2BHzy1iqE0PGAz6TxsLOy6p2RRiuZ%2BZMYAGVCzCd3eT%2FEwZTbJVf2WKqkloyS1ucgQDk1gc4o9r%2BtOK05Lp8UmYH0Lc%2FqvPDVcWOMS38t3I0SBjPjM3A%3D%3D (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
2024-07-17 10:49:07,408 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2889] upload_file request headers: {'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '366'}
2024-07-17 10:49:07,408 ERROR   wandb-upload_2:26400 [internal_api.py:upload_file():2891] upload_file response body: ''
2024-07-17 10:49:08,414 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:08,414 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:09,420 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:09,420 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:10,423 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:10,424 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:11,427 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: status_report
2024-07-17 10:49:11,427 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:11,428 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:12,433 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:12,433 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
2024-07-17 10:49:13,435 DEBUG   HandlerThread:26400 [handler.py:handle_request():158] handle_request: poll_exit
2024-07-17 10:49:13,436 DEBUG   SenderThread:26400 [sender.py:send_request():406] send_request: poll_exit
